TRAIN_DATA = [
    ('details for Mira Yadav', {'entities': [(12, 22, 'name')]}),
    ('contact number for Siya Reddy', {'entities': [(19, 29, 'name')]}),
    ('find the teacher with a PhD', {'entities': [(9, 16, 'role'), (24, 27, 'education')]}),
    ('who is the admin for Library', {'entities': [(11, 16, 'role'), (21, 28, 'department')]}),
    ('get details for roll number 107', {'entities': [(28, 31, 'rollNumber')]}),
    ('whose father is Aditya Kumar', {'entities': [(16, 28, 'fatherName')]}),
    ('find student with contact 9980327308', {'entities': [(5, 12, 'role'), (26, 36, 'contact')]}),
    ('who teaches mathematics', {'entities': [(12, 23, 'subject')]}),
    ('show student in class 7B', {'entities': [(5, 12, 'role'), (22, 24, 'classSection')]}),
    ('show me the physics teacher', {'entities': [(12, 19, 'subject'), (20, 27, 'role')]}),
    ('roll number of Aarav', {'entities': [(15, 20, 'name')]}),
    ('find student in class 9C', {'entities': [(5, 12, 'role'), (22, 24, 'classSection')]}),
    ('who is head of Accounts', {'entities': [(15, 23, 'department')]}),
    ('show me roll number 42', {'entities': [(20, 22, 'rollNumber')]}),
    ('find teacher with number 9876543210', {'entities': [(5, 12, 'role'), (25, 35, 'contact')]}),
    ('find Rohan Sharma', {'entities': [(5, 17, 'name')]}),
    ('show me Kunal', {'entities': [(8, 13, 'name')]}),
    ('details for Aditya Kumar', {'entities': [(12, 24, 'name')]}),
    ('find details for Mr. Sharma', {'entities': [(17, 27, 'name')]}),
    ('who is the techer for maths?', {'entities': [(11, 17, 'role'), (22, 27, 'subject')]}),
    ('Can you tell me who the head of the Science department is?', {'entities': [(36, 43, 'department')]}),
    ('add student Aarav Kumar to class 8A', {'entities': [(4, 11, 'role'), (12, 23, 'name'), (33, 35, 'classSection')]}),
    ('create admin Isha Mehta for Accounts', {'entities': [(7, 12, 'role'), (13, 23, 'name'), (28, 36, 'department')]}),
    ('enroll Vikram Singh as a teacher for Math', {'entities': [(7, 19, 'name'), (25, 32, 'role'), (37, 41, 'subject')]}),
    ('add teacher Anita Singh subject English', {'entities': [(4, 11, 'role'), (12, 23, 'name'), (32, 39, 'subject')]}),
    ('create a new student', {'entities': [(13, 20, 'role')]}),
    ('i want to add a teacher', {'entities': [(16, 23, 'role')]}),
    ('add student named Kunal in 10A', {'entities': [(4, 11, 'role'), (18, 23, 'name'), (27, 30, 'classSection')]}),
    ('insert a new admin for HR', {'entities': [(13, 18, 'role'), (23, 25, 'department')]}),
    ('add student with father Ramesh Kumar', {'entities': [(4, 11, 'role'), (24, 36, 'fatherName')]}),
    ('create a teacher for Computer Science', {'entities': [(9, 16, 'role'), (21, 37, 'subject')]}),
    ('add vikash chahar', {'entities': [(4, 17, 'name')]}),
    ('create user Siya Reddy', {'entities': [(12, 22, 'name')]}),
    ('enroll teacher Aarav', {'entities': [(7, 14, 'role'), (15, 20, 'name')]}),
    ('register new student Rohan', {'entities': [(13, 20, 'role'), (21, 26, 'name')]}),
    ('Add a new student named Kabir, roll number 15, to class 6A', {'entities': [(10, 17, 'role'), (24, 29, 'name'), (43, 45, 'rollNumber'), (56, 58, 'classSection')]}),
    ("change Siya Reddy's contact to 9998887776", {'entities': [(7, 17, 'name'), (31, 41, 'contact')]}),
    ('update education for Prisha Yadav to PhD', {'entities': [(21, 33, 'name'), (37, 40, 'education')]}),
    ('move roll number 107 to section C', {'entities': [(17, 20, 'rollNumber'), (32, 33, 'section')]}),
    ('assign Social as new subject for Prisha Yadav', {'entities': [(7, 13, 'subject'), (33, 45, 'name')]}),
    ("update Aarav's class to 11B", {'entities': [(7, 12, 'name'), (24, 27, 'classSection')]}),
    ('correct father name for Mira', {'entities': [(24, 28, 'name')]}),
    ('change department for Isha Mehta', {'entities': [(22, 32, 'name')]}),
    ('update subject of Vikram Singh', {'entities': [(18, 30, 'name')]}),
    ('edit Vikram Singh', {'entities': [(5, 17, 'name')]}),
    ('update Reyansh Patel', {'entities': [(7, 20, 'name')]}),
    ('change details for Anita', {'entities': [(19, 24, 'name')]}),
    ("update Mr. Kumar's phone number to 8877665544", {'entities': [(7, 16, 'name'), (35, 45, 'contact')]}),
    ('assign Physics to Mr. Singh', {'entities': [(7, 14, 'subject'), (18, 27, 'name')]}),
    ("change a student's father name", {'entities': [(9, 16, 'role')]}),
    ('block Mira Yadav', {'entities': [(6, 16, 'name')]}),
    ('i want to block vikash chahar', {'entities': [(16, 29, 'name')]}),
    ('block student with father Aditya Kumar', {'entities': [(6, 13, 'role'), (26, 38, 'fatherName')]}),
    ('block admin from Library', {'entities': [(6, 11, 'role'), (17, 24, 'department')]}),
    ('block contact 9701758896', {'entities': [(14, 24, 'contact')]}),
    ('remove roll number 55', {'entities': [(19, 21, 'rollNumber')]}),
    ('delete teacher Anita Singh', {'entities': [(7, 14, 'role'), (15, 26, 'name')]}),
    ('block meera yadav', {'entities': [(6, 17, 'name')]}),
    ('remove Isha Mehta', {'entities': [(7, 17, 'name')]}),
    ('delete Prisha', {'entities': [(7, 13, 'name')]}),
    ('block yadav', {'entities': [(6, 11, 'name')]}),
    ('Roll number 88, please remove them', {'entities': [(12, 14, 'rollNumber')]}),
    ('block students Aarav and Mira', {'entities': [(6, 14, 'role'), (15, 20, 'name'), (25, 29, 'name')]}),
    ('promote student with roll 107', {'entities': [(8, 15, 'role'), (26, 29, 'rollNumber')]}),
    ('promote Reyansh Patel to head of Library', {'entities': [(8, 21, 'name'), (33, 40, 'department')]}),
    ('promote the english teacher', {'entities': [(12, 19, 'subject'), (20, 27, 'role')]}),
    ('promote Siya', {'entities': [(8, 12, 'name')]}),
    ('assign head admin to Isha Mehta', {'entities': [(21, 31, 'name')]}),
    ('promote Mira Yadav', {'entities': [(8, 18, 'name')]}),
    ('Okay, now please go ahead and promote Isha Mehta to be the new head of the HR department', {'entities': [(38, 48, 'name'), (75, 77, 'department')]}),
    ('Mira Yadav', {'entities': [(0, 10, 'name')]}),
    ('Siya Reddy', {'entities': [(0, 10, 'name')]}),
    ('student Aarav Kumar class 7', {'entities': [(0, 7, 'role'), (8, 19, 'name'), (26, 27, 'className')]}),
    ('teacher Prisha', {'entities': [(0, 7, 'role'), (8, 14, 'name')]}),
    ('admin Isha Mehta', {'entities': [(0, 5, 'role'), (6, 16, 'name')]}),
    ('roll number 12', {'entities': [(12, 14, 'rollNumber')]}),
    ('class 5B', {'entities': [(6, 8, 'classSection')]}),
    ('contact 9123456789', {'entities': [(8, 18, 'contact')]}),
    ('Mr. Patel', {'entities': [(0, 9, 'name')]}),
    ('class 8 section C', {'entities': [(16, 17, 'section'), (6, 7, 'className')]}),
    ('detials for Riya', {'entities': [(12, 16, 'name')]}),
]
